<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var App\Entity\User $user
 */

$this->layout('layouts::site');
?>

<div class="container page">
    <h1 class="section-title">My Dashboard</h1>

    <div class="row">
        <div class="col-lg-5 col-md-6">
            <div class="card mb-3">
                <div class="card-body d-flex align-items-center">
                    <div class="flex-shrink-0 ts-profile-picture me-3"
                         style="width: 100px; height: 100px; background-image: url('<?=avatarUrl($user['user_img']) ?>')">
                    </div>
                    <div class="flex-fill">
                        <h2><?= escapeHtml($user['username']) ?></h2>
                        <div class="badges">
                            <?php
                            $pronouns = trim($user['pronouns'] ?? '');
                            if (!empty($pronouns)) : ?>
                                <span class="badge text-bg-info">
                                    <?= escapeHtml($pronouns) ?>
                                </span>
                            <?php
                            endif; ?>
                            <?php
                            $title = trim($user['title'] ?? '');
                            if (empty($title)) {
                                $title = 'Team Member';
                            }

                            if ($user['is_team'] == 1) : ?>
                                <span class="badge text-bg-success">
                                <?= escapeHtml($title) ?>
                            </span>
                            <?php
                            endif; ?>
                        </div>
                    </div>
                </div>
                <div class="list-group list-group-flush">
                    <a class="list-group-item list-group-item-action"
                       href="<?= $router->urlFor('profile', ['user' => $user['username']]) ?>">
                        <i class="bi-person"></i> View Public Profile
                    </a>
                    <a class="list-group-item list-group-item-action"
                       href="<?= $router->urlFor('dashboard:profile') ?>">
                        <i class="bi-person-gear"></i> Edit My Profile
                    </a>
                    <a class="list-group-item list-group-item-action"
                       href="<?= $router->urlFor('dashboard:password') ?>">
                        <i class="bi-key-fill"></i> Change My Password
                    </a>
                </div>
            </div>
        </div>
        <div class="col-lg-7 col-md-6">
            <div class="row">
                <div class="col-lg-6 col-md-12 mb-3 mb-lg-0">
                    <div class="card">
                        <h3 class="card-header">Site Features</h3>
                        <div class="list-group list-group-flush">
                            <a class="list-group-item list-group-item-action"
                               href="<?= $router->urlFor('dashboard:posters') ?>">
                                <i class="bi-file-image-fill"></i> Poster Network
                            </a>
                            <a class="list-group-item list-group-item-action"
                               href="<?= $router->urlFor('dashboard:skills') ?>">
                                <i class="bi-stars"></i> My Skills
                            </a>

                            <?php if ($user->isMod()): ?>
                                <a class="list-group-item list-group-item-action"
                                   href="<?= $router->urlFor('dashboard:short_urls') ?>">
                                    <i class="bi-link"></i> Short URLs
                                </a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php
                if ($user->isAdmin()): ?>
                <div class="col-lg-6 col-md-12">
                    <div class="card">
                        <h3 class="card-header">Administration</h3>

                        <div class="list-group list-group-flush">
                            <a class="list-group-item list-group-item-action"
                               href="<?= $router->urlFor('dashboard:admin:users') ?>">
                                <i class="bi-people"></i> User Management
                            </a>
                            <a class="list-group-item list-group-item-action"
                               href="<?= $router->urlFor('dashboard:admin:add_world') ?>">
                                <i class="bi-globe2"></i> Add VRChat World
                            </a>
                        </div>
                    </div>
                </div>
                <?php
                endif; ?>
            </div>
        </div>
    </div>
</div>
