<?php

/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var string|null $error
 */
$this->layout('layouts::dashboard');
?>

<?= $this->fetch('common/breadcrumbs', [
    'urls' => [
        $router->urlFor('dashboard') => 'My Dashboard',
    ],
    'current' => 'Change My Password',
]) ?>

<h1>Change My Password</h1>

<?php
if ($error) : ?>
    <div class="alert alert-danger">
        <b>Error:</b> <?= escapeHtml($error) ?>
    </div>
<?php
endif; ?>

<form action="" method="post">
    <div class="card">
        <div class="card-body">
            <div class="row mb-2">
                <div class="col-md-6">
                    <div class="form-label-group">
                        <label>
                            Current Password:
                            <input type="password" class="form-control form-control-secondary"
                                   name="current_password" autocomplete="current_password" required>
                        </label>
                    </div>
                </div>
            </div>

            <div class="row mb-2">
                <div class="col-md-4">
                    <div class="form-label-group">
                        <label>
                            Create New Password:
                            <input type="password" class="form-control form-control-secondary" id="passwordField"
                                   name="new_password" autocomplete="new-password" required>
                        </label>
                        <div class="progress mt-2">
                            <div class="progress-bar" id="passwordStrengthBar" role="progressbar"
                                 style="width: 0%" aria-valuenow="0" aria-valuemin="0"
                                 aria-valuemax="100"></div>
                        </div>
                        <small id="passwordStrengthText" class="form-text text-muted"></small>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-label-group">
                        <label>
                            Verify New Password:
                            <input type="password" class="form-control form-control-secondary"
                                   name="new_password_confirm" autocomplete="new-password" required>
                        </label>
                    </div>
                </div>
            </div>

            <button type="submit" class="btn btn-lg btn-primary">Change Password</button>
        </div>
    </div>
</form>

<script>
    ready(() => {
        passwordStrength();
    });
</script>
