<?php
/**
 * @var League\Plates\Template\Template $this
 */

// TODO: Populate before next Foxxcon
$this->layout('layouts::site');
?>

<div class="fxcn">
    <div id="video-container">
        <video id="header-video" src="videos/bg-no-logo-2.mp4" autoplay muted loop></video>
    </div>

    <section class="page-section"
             style="background-color: rgba(1,24,46,0.9); text-align: left; padding-top: 6rem; padding-bottom: 6rem; font-size: 1.1rem; color: white;">
        <div class="container">
            <div class="fxcn-buttons">
                <h2>VRChat Instances</h2>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=68031~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(use)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#f00">Red</b></a><br>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=60130~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(use)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#0f0">Green</b></a><br>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=14221~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(use)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#0ff">Blue</b></a><br>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=48048~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(use)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#ff0">Yellow</b></a><br>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=92881~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(us)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#f0f">Magenta</b></a><br>
                <a href="https://vrchat.com/home/launch?worldId=wrld_27806231-964b-4fbe-add8-10bf14be8071&instanceId=05639~group(grp_41df2df4-be4e-4a4e-be5e-eabb1425c4e5)~groupAccessType(public)~region(us)"
                   class="btn btn-lg btn-success" style="padding: 20px; margin:5px;"> Foxxcon Cyberpunk Instance <b
                        style="color:#fff">White</b></a><br>
            </div>
        </div>
    </section>
</div>
