<?php
/** @var League\Plates\Template\Template $this */

$this->fetch('common/frontend_assets', [
    'component' => 'frontend/layout.js',
])
?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <?php
    require(__DIR__ . '/sections/header.phtml'); ?>
</head>
<body>

<header>
    <nav class="navbar fixed-top navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="/static/img/logo-with-logotype.svg" style="width: 211px; height: 45px;"
                     alt="WaterWolf Family: We Build Adventure and Friendship">
            </a>
        </div>
    </nav>
</header>

<main id="main">
    <?= $this->section('content') ?>
</main>

<footer id="footer" class="mt-3">
    <?php
    require(__DIR__ . '/sections/footer.phtml'); ?>
</footer>
</body>
</html>
