<?php
/** @var League\Plates\Template\Template $this */

$this->fetch('common/frontend_assets', [
    'component' => 'frontend/layout.js',
])
?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <?php
    require(__DIR__ . '/sections/header.phtml'); ?>
</head>
<body>
<?php
require(__DIR__ . '/sections/nav.phtml'); ?>

<main id="main">
    <?= $this->section('content') ?>
</main>

<footer id="footer" class="mt-3">
    <?php
    require(__DIR__ . '/sections/footer.phtml'); ?>
</footer>

<?php
require(__DIR__ . '/sections/notifications.phtml'); ?>
</body>
</html>
