<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var string|null $error
 */

$this->layout('layouts::dashboard');
?>

<?= $this->fetch('common/breadcrumbs', [
    'urls' => [
        $router->urlFor('dashboard') => 'My Dashboard',
    ],
    'current' => 'Add VRChat World',
]) ?>

<h1>Add VRChat World</h1>

<?php
if ($error) : ?>
    <div class="alert alert-danger">
        <b>Error:</b> <?= escapeHtml($error) ?>
    </div>
<?php
endif; ?>

<form action="" method="post">
    <div class="form-label-group mb-2">
        <label for="id">VRChat World ID:</label>
        <input class="form-control form-control-secondary" type="text" id="id" name="id" required>
    </div>

    <button type="submit" class="btn btn-primary">Submit to Database</button>
</form>
