<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var array $users
 */

$this->layout('layouts::dashboard');
?>

<?= $this->fetch('common/breadcrumbs', [
    'urls' => [
        $router->urlFor('dashboard') => 'My Dashboard',
    ],
    'current' => 'User Management',
]) ?>

<h1>User Management</h1>

<input id="myInput" class="form-control" value="<?= escapeHtmlAttribute($_GET['s'] ?? null) ?>"
       type="text" Placeholder="Search for Users"/>

<br>

<table class="table table-sm table-striped table-bordered align-middle" id="myTable">
    <thead>
    <tr>
        <th scope="col" style="width:10%">UID</th>
        <th scope="col">Username</th>
        <th scope="col" style="width:10%">Admin?</th>
        <th scope="col" style="width:10%">Mod?</th>
        <th scope="col" style="width:10%">Team?</th>
        <th scope="col" style="width:10%">DJ?</th>
        <th scope="col" style="width:10%">Banned?</th>
        <th scope="col" style="width:15%">Action</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($users as $row) {
        ?>
        <tr>
            <th scope="row"> <?= escapeHtml($row['id']) ?></th>
            <td><?= escapeHtml($row['username']) ?></td>
            <?php
            if ($row['is_admin'] === 1) : ?>
                <td class="text-bg-success">Yes</td>
            <?php
            else : ?>
                <td class="text-muted">No</td>
            <?php
            endif; ?>
            <?php
            if ($row['is_mod'] === 1) : ?>
                <td class="text-bg-success">Yes</td>
            <?php
            else : ?>
                <td class="text-muted">No</td>
            <?php
            endif; ?>
            <?php
            if ($row['is_team'] === 1) : ?>
                <td class="text-bg-success">Yes</td>
            <?php
            else : ?>
                <td class="text-muted">No</td>
            <?php
            endif; ?>
            <?php
            if ($row['is_dj'] === 1) : ?>
                <td class="text-bg-success">Yes</td>
            <?php
            else : ?>
                <td class="text-muted">No</td>
            <?php
            endif; ?>
            <?php
            if ($row['banned'] === 1) : ?>
                <td class="text-bg-danger">Yes</td>
            <?php
            else : ?>
                <td class="text-muted">No</td>
            <?php
            endif; ?>
            <td>
                <a href="<?= $router->urlFor('dashboard:profile', ['id' => $row['id']]) ?>"
                   class="btn btn-primary btn-sm">
                    Edit
                </a>
                <a href="<?= $router->urlFor('profile', ['user' => $row['username']]) ?>"
                   class="btn btn-secondary btn-sm">
                    View
                </a>
            </td>
        </tr>
        <?php
    } ?>
    </tbody>
</table>

<script>
    function filterTable(event) {
        var filter = event.target.value.toUpperCase();
        var rows = document.querySelector("#myTable tbody").rows;

        for (var i = 0; i < rows.length; i++) {
            var FirstName = rows[i].cells[1].textContent.toUpperCase();
            var Address = rows[i].cells[3].textContent.toUpperCase();
            var LastName = rows[i].cells[2].textContent.toUpperCase();
            if (FirstName.indexOf(filter) > -1 || Address.indexOf(filter) > -1 || LastName.indexOf(filter) > -1) {
                rows[i].style.display = "";
            } else {
                rows[i].style.display = "none";
            }
        }
    }

    document.querySelector('#myInput').addEventListener('load', filterTable, false);
    document.querySelector('#myInput').addEventListener('keyup', filterTable, false);
</script>
