services:
  web:
    image: waterwolfdev/waterwolf-site:development
    build:
      context: .
      target: development
    depends_on:
      - db
    volumes:
      - .:/var/app/www
    env_file:
        - dev.env
    environment:
      MARIADB_SERVER: db
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    logging: &default-logging
      options:
        max-size: "1m"
        max-file: "5"

  db:
    image: docker.io/library/mariadb:lts
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - dev.env
    ports:
      - "127.0.0.1:13306:3306"
    logging: *default-logging

volumes:
  db_data: { }
