<?php
/**
 * @var League\Plates\Template\Template $this
 * @var string $name
 * @var string|null $id
 * @var array<array-key, mixed> $options
 * @var mixed|null $selected
 */

$id ??= $name;
$selected ??= '';
?>

<select class="form-select" name="<?= escapeHtmlAttribute($name) ?>"
        id="<?= escapeHtmlAttribute($id) ?>">
    <?php
    foreach ($options as $optionKey => $optionText): ?>
        <option value="<?= escapeHtmlAttribute($optionKey) ?>"
                <?php
                if ((string)$selected === (string)$optionKey): ?>selected<?php
        endif; ?>
        >
            <?= escapeHtml($optionText) ?>
        </option>
    <?php
    endforeach; ?>
</select>
