<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var array $shortUrls
 */

$this->layout('layouts::dashboard');
?>

<?= $this->fetch('common/breadcrumbs', [
    'urls' => [
        $router->urlFor('dashboard') => 'My Dashboard',
    ],
    'current' => 'Short URLs',
]) ?>

<h1>Short URLs</h1>

<div class="card">
    <h2 class="card-header">View Short URLs</h2>
    <div class="card-body">
        <div class="buttons mb-3">
            <a class="btn btn-lg btn-success" href="<?= $router->urlFor('dashboard:short_urls:create') ?>">
                <i class="bi-plus-circle-fill" aria-hidden="true"></i> Add Short URL
            </a>
        </div>

        <table class="table table-striped table-bordered table-hover align-middle">
            <thead>
            <tr>
                <th>Short URL</th>
                <th>Long URL</th>
                <th>Views</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php
            foreach ($shortUrls as $row) : ?>
                <tr>
                    <th scope="col"><code><?= escapeHtml($row['short_url']) ?></code></th>
                    <td><?= escapeHtml($row['long_url']) ?></td>
                    <td><?= escapeHtml($row['views']) ?></td>
                    <td>
                        <a class="btn btn-sm btn-warning"
                           href="<?= $router->urlFor('dashboard:short_urls:edit', ['id' => $row['id']]) ?>">
                            Edit
                        </a>
                        <a class="btn btn-sm btn-danger"
                           href="<?= $router->urlFor('dashboard:short_urls:delete', ['id' => $row['id']]) ?>">
                            Delete
                        </a>
                    </td>
                </tr>
            <?php
            endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
