<?php
/**
 * @var League\Plates\Template\Template $this
 * @var App\Session\Flash $flash
 */

?>
<div class="toast-container position-fixed top-0 end-0 p-3">
    <?php
    $messages = $flash->getMessages();
    if (count($messages) > 0):
        foreach ($messages as $message):
            ?>
            <div
                class="toast align-items-center toast-notification text-bg-<?= $message['color'] ?>"
                role="alert" aria-live="assertive" aria-atomic="true">
                <div class="d-flex">
                    <div class="toast-body">
                        <?= $message['text'] ?>
                    </div>
                    <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast"
                            aria-label="Close"></button>
                </div>
            </div>
        <?php
        endforeach;
    endif;
    ?>
</div>
