<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var string|null $error
 * @var string|null $return
 */

$this->layout('layouts::site');
?>

<video class="bg-video" loading="lazy" loop="loop" autoplay muted="muted" volume="0">
    <source src="/static/video/login.mp4" type="video/mp4">
    <source src="/static/video/login.webm" type="video/webm">
</video>

<div class="container page">
    <div class="card mx-auto" style="max-width: 400px;">
        <h1 class="card-header">Log In</h1>
        <div class="card-body">
            <form class="form-signin" action="" method="POST" id="login-form">
                <?php
                if ($error) : ?>
                    <div class="alert alert-danger">
                        <b>Error:</b> <?= escapeHtml($error) ?>
                    </div>
                <?php
                endif; ?>

                <div class="form-label-group">
                    <label for="inputEmail">Username or E-mail:</label>
                    <input type="text" id="inputEmail" class="form-control form-control-lg" name="username"
                           placeholder="Username" autocomplete="username" required autofocus>
                </div>

                <div class="form-label-group mt-2">
                    <label for="inputPassword">Password:</label>
                    <input type="password" id="inputPassword" class="form-control form-control-lg" name="pass"
                           placeholder="Password" autocomplete="current_password" required>
                    <span class="form-text">
                        <a href="<?= $router->urlFor('forgot') ?>">Forgot your password?</a>
                    </span>
                </div>

                <input type="hidden" name="return" value="<?= escapeHtmlAttribute($return) ?>">

                <div class="mt-3 d-grid gap-2">
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
                </div>

                <p class="my-2 text-center">
                    Don't have an account? Create one today!
                </p>

                <div class="d-grid gap-2">
                    <a href="<?= $router->urlFor('register') ?>" class="btn btn-success btn-block">Create Account</a>
                </div>

                <p class="mt-2 mb-0 text-muted text-center">&copy;<?= date('Y') ?> - A WaterWolf Network Service.<br>
                    <small>WaterWolf and its affiliated websites are not affiliated with VRChat or its
                        partners.</small>
                </p>
            </form>
        </div>
    </div>
</div>
