<?php
/**
 * @var League\Plates\Template\Template $this
 * @var string|null $error
 * @var array $data
 */

$this->layout('layouts::site');
?>

<video class="bg-video" loading="lazy" loop="loop" autoplay muted="muted" volume="0">
    <source src="/static/video/register.mp4" type="video/mp4">
    <source src="/static/video/register.webm" type="video/webm">
</video>

<div class="container page">
    <?php
    if (!empty($data['ref'])) { ?>
        <div class="card mb-4 mx-auto" style="max-width: 700px;">
            <h5 class="card-header">You have been referred by:</h5>
            <div class="card-body">
                <h1>
                    <?= escapeHtml($data['ref']) ?>
                </h1>
            </div>
        </div>
        <?php
    } ?>

    <div class="card mx-auto" style="max-width:700px;">
        <div class="card-header">
            <h2 class="card-title m-0">Register to WaterWolf</h2>
        </div>
        <div class="card-body">
            <?php
            if ($error) : ?>
                <div class="alert alert-danger">
                    <b>Error:</b> <?= escapeHtml($error) ?>
                </div>
            <?php
            endif; ?>

            <form name="register" method="post">
                <input type="hidden" name="ref" value="<?= escapeHtmlAttribute($data['ref'] ?? '') ?>">
                <div class="row mb-2">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="reg_username" class="form-label">Username:</label>
                            <input type="text" class="form-control form-control-secondary"
                                   id="reg_username" name="reg_username"
                                   autocomplete="off" placeholder="Username" maxlength="24"
                                   value="<?= escapeHtmlAttribute($data['reg_username'] ?? '') ?>" required>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="reg_email" class="form-label">E-mail Address:</label>
                            <input type="email" class="form-control form-control-secondary"
                                   id="reg_email" name="reg_email"
                                   placeholder="email@place.com"
                                   value="<?= escapeHtmlAttribute($data['reg_email'] ?? '') ?>" required>
                        </div>
                    </div>
                </div>

                <div class="row mb-2">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="passwordField" class="form-label">Create Password:</label>
                            <input type="password" class="form-control form-control-secondary" id="passwordField"
                                   name="reg_pass" placeholder="*****" required>

                            <div class="progress mt-2">
                                <div class="progress-bar" id="passwordStrengthBar" role="progressbar"
                                     style="width: 0%" aria-valuenow="0" aria-valuemin="0"
                                     aria-valuemax="100"></div>
                            </div>
                            <small id="passwordStrengthText" class="form-text text-muted"></small>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="reg_pass_confirm" class="form-label">Verify Same Password:</label>
                            <input type="password" class="form-control form-control-secondary"
                                   id="reg_pass_confirm" name="reg_pass_confirm" placeholder="*****" required>
                        </div>
                    </div>
                </div>

                <div class="form-group mb-2">
                    <label for="vrchat_username" class="form-label">VRChat Username:</label>
                    <input type="text" class="form-control form-control-secondary"
                           id="vrchat_username" name="vrchat_username"
                           maxlength="24"
                           placeholder="ChuckNorris" required>
                </div>

                <div class="form-group mb-2">
                    <label for="discord_username" class="form-label">Discord Username:</label>
                    <input type="text" class="form-control form-control-secondary"
                           id="discord_username" name="discord_username"
                           maxlength="24"
                           placeholder="ChuckNorris#0001" required>
                </div>

                <div class="form-group mb-2">
                    <label for="reg_country" class="form-label">Country Of Origin:</label>
                    <select name="reg_country" class="form-select" id="reg_country">
                        <?= $this->fetch('common/countries') ?>
                    </select>
                </div>

                <div class="buttons mt-3 d-grid gap-2">
                    <button type="submit" class="btn btn-lg btn-primary btn-block">
                        <i class="bi-plus-circle" aria-hidden="true"></i>
                        Create Account
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    ready(() => {
        passwordStrength();
    });
</script>
