<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var string $baseUrl
 * @var array $groups
 * @var array $types
 */

$exampleGroup = $groups[array_key_last($groups)];
$exampleType = $types[array_key_last($types)];

$this->layout('layouts::site');
?>

<div class="container page">
    <h1 class="section-title">The WaterWolf Poster Network</h1>

    <div class="card">
        <div class="card-body">
            <div class="buttons mb-2">
                <a class="btn btn-primary btn-lg" href="<?= $router->urlFor('dashboard:posters') ?>">
                    Access the Poster Network
                </a>
            </div>

            <p class="card-text">The WaterWolf poster network allows you to easily upload and manage posters that are in
                a uniform size and
                format and can be used in VRChat worlds, promotional materials, and more.</p>

            <h2>Using the Poster Network</h2>

            <div class="row">
                <div class="col">
                    <h3>Loading a Random Poster</h3>

                    <p class="card-text">If you want to load a completely random poster from the uploaded collection,
                        load the
                        base URL with no query parameters:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <a class="alert-link" href="<?= $baseUrl ?>"><?= $baseUrl ?></a>
                        </code>
                    </p>
                </div>
                <div class="col">
                    <h3>Loading a Specific Poster by ID</h3>

                    <p class="card-text">You can reference a specific poster by adding its ID:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <?= $baseUrl ?>?pid=123
                        </code>
                    </p>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col">
                    <h3>Filtering by Group</h3>

                    <p class="card-text">Posters can be uploaded for, and managed by, specific groups. You can filter
                        posters by which group owns it:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <?= $baseUrl ?>?group=<?=escapeHtml($exampleGroup['id']) ?>
                        </code>
                    </p>

                    <p class="card-text">These groups are available:</p>

                    <ul>
                        <?php
                        foreach ($groups as $group) : ?>
                            <li><code><?= escapeHtml($group['id']) ?></code>: <?= escapeHtml(
                                    $group['name']
                                ) ?></li>
                        <?php
                        endforeach; ?>
                    </ul>

                    <h3>Filtering by Poster Type</h3>

                    <p class="card-text">You can limit your selection to specific types of posters:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <?= $baseUrl ?>?type=<?=escapeHtml($exampleType['id']) ?>
                        </code>
                    </p>

                    <p class="card-text">These types are available:</p>

                    <ul>
                        <?php
                        foreach ($types as $type) : ?>
                            <li><code><?= escapeHtml($type['id']) ?></code>: <?= escapeHtml(
                                    $type['description']
                                ) ?>
                            </li>
                        <?php
                        endforeach; ?>
                    </ul>
                </div>
                <div class="col">
                    <h3>Filtering by Collection</h3>

                    <p class="card-text">Posters can optionally be part of a "collection" to make them easy to reference
                        in your worlds:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <?= $baseUrl ?>?collection=ww_events
                        </code>
                    </p>

                    <p class="card-text">More than one poster be in a collection; the poster that appears will be
                        shuffled between them. Collections aren't unique to groups, but you can chain filters
                        (see below) to select only posters owned by a group with a given collection.</p>

                    <h3>Chaining Filters</h3>

                    <p class="card-text">You can combine the queries above to narrow your filter, for example, to only
                        show
                        posters that meet multiple criteria:</p>

                    <p class="card-text">
                        <code class="p-2 text-info-emphasis bg-info-subtle border border-info-subtle rounded-3">
                            <?= $baseUrl ?>?group=<?=escapeHtml($exampleGroup['id']) ?>&type=<?=escapeHtml($exampleType['id']) ?>
                        </code>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
