<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 * @var array $types
 * @var array $groups
 */

$this->layout('layouts::dashboard');
?>

<?= $this->fetch('common/breadcrumbs', [
    'urls' => [
        $router->urlFor('dashboard') => 'My Dashboard',
    ],
    'current' => 'Poster Network',
]) ?>

<h1>Poster Network</h1>

<div class="card">
    <div class="card-header">
        <h2>View Posters</h2>

        <ul class="nav nav-tabs card-header-tabs" role="tablist">
            <?php
            foreach ($groups as $groupId => $group) : ?>
                <li class="nav-item">
                    <button class="nav-link <?php
                    if ($groupId === '_mine') :
                        ?>active<?php
                    endif; ?>"
                            data-bs-toggle="tab" data-bs-target="#tab_<?= escapeHtmlAttribute($groupId) ?>"
                            type="button" role="tab" aria-controls="tab_<?= escapeHtmlAttribute($groupId) ?>"
                            aria-selected="true"><?= $group['name'] ?></button>
                </li>
            <?php
            endforeach; ?>

            <div class="ms-auto">
                <a href="<?= $router->urlFor('dashboard:posters:create') ?>" class="btn btn btn-success">Upload a New
                    Poster</a>
            </div>
        </ul>
    </div>

    <div class="card-body tab-content">
        <?php
        foreach ($groups as $groupId => $group) : ?>
            <div class="tab-pane fade <?php
            if ($groupId === '_mine') :
                ?>active show<?php
            endif; ?>" id="tab_<?= escapeHtmlAttribute($groupId) ?>"
                 role="tabpanel">
                <div class="row"> <!-- Start of the grid container -->
                    <?php
                    foreach ($group['posters'] as $poster) { ?>
                        <div class="col-md-3 col-sm-6">
                            <!-- Each poster takes up 1/4 of the width on medium screens and 1/2 on small screens. Adjust as needed. -->
                            <div class="card mb-1">
                                <!-- Added margin-bottom for spacing between cards in the grid -->
                                <div class="card-body">
                                    <a href="<?= $router->urlFor('posters', ['id' => $poster['id']]) ?>"
                                       target="_blank">
                                        <img src="<?= $poster['mediaUrl'] ?>" class="img-fluid" alt="Poster"/>
                                    </a>

                                    <?php
                                    if ($groupId === '_community') : ?>
                                        <div>Creator: <?= escapeHtml($poster['username']) ?></div>
                                    <?php
                                    endif; ?>

                                    <?php
                                    if ($poster['isExpired']) : ?>
                                        <div class="text-danger">Expired</div>
                                    <?php
                                    elseif ($poster['expiresAtText']) : ?>
                                        <div class="text-warning">Expires <?= $poster['expiresAtText'] ?></div>
                                    <?php
                                    endif; ?>

                                    <?php
                                    if ($poster['collection']) : ?>
                                        <div>Collection: <code><?= escapeHtml(
                                                    $poster['collection']
                                                ) ?></code></div>
                                    <?php
                                    endif; ?>

                                    <?php
                                    if ($poster['type_id']) : ?>
                                        <div>Type: <?= escapeHtml($types[$poster['type_id']]) ?></div>
                                    <?php
                                    endif; ?>

                                    <?php
                                    if ($group['canEdit']) : ?>
                                        <div>Views: <?= escapeHtml($poster['views']) ?></div>

                                        <div class="btn-group btn-group-sm mt-2">
                                            <a href="<?= $router->urlFor(
                                                'dashboard:posters:edit',
                                                ['id' => $poster['id']]
                                            ) ?>"
                                               class="btn btn-warning btn-sm">
                                                <i class="bi-pencil-fill" aria-hidden="true"></i> Edit
                                            </a>
                                            <a href="<?= $router->urlFor(
                                                'dashboard:posters:delete',
                                                ['id' => $poster['id']]
                                            ) ?>"
                                               class="btn btn-danger btn-sm" data-confirm-danger="Remove poster?">
                                                <i class="bi-trash" aria-hidden="true"></i> Remove
                                            </a>
                                        </div>
                                    <?php
                                    endif; ?>
                                </div>
                            </div>
                        </div>
                        <?php
                    } ?>
                </div> <!-- End of the grid container -->
            </div>
        <?php
        endforeach; ?>
    </div>
</div>
