<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Throwable $exception
 */

$this->layout('layouts::minimal');
?>

<div class="container page">
    <div class="card mx-auto" style="max-width: 400px;">
        <div class="card-header">
            <h2 class="card-title m-0">HTTP Error <?= escapeHtml($exception->getCode()) ?></h2>
        </div>
        <div class="card-body">
            <p class="card-text"><?= escapeHtml($exception->getMessage()) ?></p>
        </div>
    </div>
</div>
