<?php
/**
 * @var League\Plates\Template\Template $this
 * @var Slim\Interfaces\RouteParserInterface $router
 */

$this->layout('layouts::site');

// Times in the configured zone below (currently EST/EDT)
$tz = 'America/New_York';

/**
 * @var array<array{
 *      name: string,
 *      time: string,
 *      timestamp: int,
 *      datetime: DateTimeImmutable,
 * }> $djs
 */
$djs = [
    [
        'name' => 'Beamflare',
        'time' => '2024-03-09 15:00',
    ],
    [
        'name' => 'Birds of Prey',
        'time' => '2024-03-09 16:00',
    ],
    [
        'name' => 'Blaze/Poptart',
        'time' => '2024-03-09 17:00',
    ],
    [
        'name' => 'Beeb',
        'time' => '2024-03-09 18:00',
    ],
    [
        'name' => 'Draven',
        'time' => '2024-03-09 19:00',
    ],
    [
        'name' => 'P I N K',
        'time' => '2024-03-09 20:00',
    ],
    [
        'name' => 'DJ Altro',
        'time' => '2024-03-09 21:00',
    ],
    [
        'name' => 'GOM8 (feat. Special Guest)',
        'time' => '2024-03-09 22:00',
    ],
    [
        'name' => 'Physwolf',
        'time' => '2024-03-09 23:00',
    ],
    [
        'name' => 'Morganite',
        'time' => '2024-03-10 00:00',
    ],
    [
        'name' => 'Warned1',
        'time' => '2024-03-10 01:00',
    ],
    [
        'name' => 'Sebris',
        'time' => '2024-03-10 03:00',
    ],
];

foreach ($djs as &$dj) {
    $dj['datetime'] = new \DateTimeImmutable($dj['time'], new DateTimeZone($tz));
    $dj['timestamp'] = $dj['datetime']->getTimestamp();
    $dj['time'] = $dj['datetime']->format('g:ia');
}
unset($dj);

$startDate = $djs[0]['timestamp'];
?>

<video loading="lazy" loop="loop" autoplay muted="muted" volume="0" class="bg-video">
    <source src="/static/defective/bg_video.webm" type="video/webm">
    <source src="/static/defective/bg_video.mp4" type="video/mp4">
</video>

<div class="content">
    <div class="text-center fw-bold mb-3">
        <!-- Logo -->
        <img src="/static/defective/logo.png" style="max-width: 400px; margin: 75px 0 25px 0;"
             alt="Defective Equipment">

        <div style="text-shadow: 1px 1px #000" class="my-3">
            <div class="fs-2 fw-bolder">A VRChat Club Experience by WaterWolf</div>
            <div class="fs-4">March 9, 2024</div>
            <div class="fs-5" id="countdown"></div>
        </div>

        <div class="buttons">
            <a href="https://www.twitch.tv/waterwolfvr" class="btn btn-lg btn-primary">
                <i class="bi-twitch" aria-hidden="true"></i> Twitch Stream
            </a>
            <a href="<?= $router->urlFor('register') ?>" class="btn btn-lg btn-success">
                <i class="bi-key-fill" aria-hidden="true"></i> Create Account
            </a>
            <a href="<?= $router->urlFor('discord') ?>" class="btn btn-lg btn-secondary">
                <i class="bi-discord" aria-hidden="true"></i> Join the Discord
            </a>
        </div>
    </div>

    <div class="container page">
        <div class="card mb-3">
            <div class="ratio ratio-16x9">
                <video id="videoPlayer" class="card-img" width="640" height="360" controls>
                    <source src="/static/defective/fullvideo.mp4" type="video/mp4">
                    Your browser does not support the video tag.
                </video>
            </div>
        </div>

        <div class="card">
            <h2 class="card-header">DJ Lineup</h2>
            <div class="card-body">
                <table class="table table-striped table-bordered table-hover mb-0">
                    <thead>
                    <tr>
                        <th scope="col">DJ</th>
                        <th scope="col"><span id="timeHeader">Time</span></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($djs as $dj) : ?>
                        <tr>
                            <td>
                                <?= escapeHtml($dj['name']) ?>
                            </td>
                            <td>
                                <time data-timestamp="<?= escapeHtmlAttribute((string)$dj['timestamp']) ?>">
                                    <?= escapeHtml($dj['time']) ?>
                                </time>
                            </td>
                        </tr>
                    <?php
                    endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    ready(function () {
        const tz = <?=json_encode($tz) ?>;
        let now = nowToDateTime(tz);

        // DJ times
        document.querySelectorAll('[data-timestamp]').forEach((item) => {
            const rowDt = timestampToDateTime(item.dataset.timestamp, tz).setZone('system');
            const rowFromNow = rowDt.diffNow('days');

            let rowText = dateTimeToTimeString(rowDt);
            if (rowFromNow < 1 && rowFromNow > -1) {
                rowText += ' (' + rowDt.toRelative() + ')';
            }

            item.innerText = rowText;
        });

        document.getElementById('timeHeader').innerText = 'Time (Local)';

        // Countdown
        const countDownDate = timestampToDateTime(<?=json_encode($startDate) ?>, tz);
        let countdown = setInterval(function () {
            now = nowToDateTime(tz);

            if (countDownDate < now) {
                clearInterval(countdown);
                document.getElementById("countdown").innerHTML = "EVENT STARTED";
            } else {
                document.getElementById("countdown").innerHTML = countDownDate.toRelative();
            }
        }, 1000);
    });
</script>
