<?php

/** @var League\Plates\Template\Template $this */
$this->layout('layouts::site');
?>

<div class="container page">
    <h1 class="section-title">Donate</h1>
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">WaterWolf - The Future of VRChat Adventures</h2>
            <p class="card-text">
                Imagine a place where the boundaries of virtual reality are constantly pushed, where adventures are
                crafted with meticulous care, and where your feedback becomes an integral part of the creation.
                Welcome to WaterWolf - a beacon of creativity and innovation in the vast universe of VRChat.
            </p>
            <p class="card-text">
                WaterWolf is more than just a name; it's a community, a collaboration of two exceptionally talented
                creators. Their unique styles and specialties converge to offer players an unparalleled journey.
                Yet, the magic doesn't stop there. The diversity and creativity embedded in WaterWolf's DNA set it
                apart. As players, we're always hungry for new adventures, new worlds, and novel experiences.
                WaterWolf not only satiates this hunger but goes above and beyond, serving up experiences that are
                fresh, captivating, and tailor-made, thanks to the invaluable feedback from its dedicated player
                base.
            </p>
            <p class="card-text">
                WaterWolf needs your support to continue its operations. By supporting WaterWolf, you're helping to
                ensure that we can continue our operations into the future. We support one-time donations via PayPal or
                monthly recurring donations via Discord's Club VIP role.
            </p>

            <h2 class="mt-4">Join the Revolution!</h2>
            <p class="card-text">Join us in this exciting journey. Donate to WaterWolf today and become a part of
                the revolution in VRChat adventures!</p>
        </div>

        <div class="card-body d-flex justify-content-center align-items-center">
            <a href="https://paypal.me/WaterwolfVR?country.x=US&locale.x=en_US"
               class="btn btn-primary py-3 px-5 me-3">Donate with Paypal to WaterWolf</a>
            <!-- <a href="https://www.patreon.com/WaterWolfFamily" class="btn btn-primary py-3 px-5">Join WaterWolf
                Patreon</a> -->
        </div>
    </div>
</div>
