<?php
/**
 * @var League\Plates\Template\Template $this
 * @var App\Media $media
 * @var array $profile
 */

$this->layout('layouts::site');

$website = $profile['website'] ?? '';
$websiteDisplay = str_replace(['http://', 'https://', 'www.'], ['', '', ''], $website);
if (!empty($website) && !str_starts_with($website, 'http')) {
    $website = 'https://' . $website;
}
?>

<div class="container page ts-style">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <div class="ts-profile-picture"
                                 style="background-image: url('<?= $media->avatarUrl($profile['user_img']) ?>')">
                            </div>
                            <div class="mt-3">
                                <h1><?= escapeHtml($profile['username']) ?></h1>
                                <div class="badges text-center">
                                    <?php
                                    $pronouns = trim($profile['pronouns'] ?? '');
                                    if (!empty($pronouns)) : ?>
                                        <span class="badge text-bg-info">
                                        <?= escapeHtml($pronouns) ?>
                                    </span>
                                    <?php
                                    endif; ?>
                                    <?php
                                    $title = trim($profile['title'] ?? '');
                                    if (empty($title)) {
                                        $title = 'Team Member';
                                    }

                                    if ($profile['is_team'] == 1) : ?>
                                        <span class="badge text-bg-success">
                                        <?= escapeHtml($title) ?>
                                    </span>
                                    <?php
                                    endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card mt-3">
                    <ul class="list-group">
                        <?php
                        if (!empty($profile['discord'])) : ?>
                            <li class="list-group-item list-group-item-dark">
                                <h5>
                                    Discord:
                                </h5>
                                <div>
                                    <?= escapeHtml($profile['discord']) ?>
                                </div>
                            </li>
                        <?php
                        endif; ?>
                        <?php
                        if (!empty($website)) : ?>
                            <li class="list-group-item list-group-item-dark">
                                <h5>
                                    Website:
                                </h5>
                                <div>
                                    <a href="<?= escapeHtmlAttribute($website) ?>">
                                        <?= escapeHtml($websiteDisplay) ?>
                                    </a>
                                </div>
                            </li>
                        <?php
                        endif; ?>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <h4 class="card-header">About Me</h4>
                    <div class="card-body">
                        <?= nl2br(escapeHtml($profile['aboutme'])) ?>
                    </div>
                </div>

                <?= $this->fetch(
                    'common/global_comments',
                    [
                        'comment_id' => 'profile_comment_' . $profile['username'],
                    ]
                ) ?>
            </div>
        </div>
    </div>
</div>
